import bcrypt from 'bcryptjs'

const data = {
    accounts: [
        {
            name: 'Admin',
            email: 'admin@example.com',
            password: bcrypt.hashSync('1234', 8),
            sex: 'male',
            avatar: '/images/avatar.jpg',
            phone:'070276372',
            isAdmin: true,
            isWebmaster: true,
        },
        {
            name: 'Long',
            email: 'Long@example.com',
            password: bcrypt.hashSync('1234', 8),
            sex: 'male',
            avatar: '/images/avt.jpg',
            phone:'0926352621',
            isAdmin: false,
            isWebmaster: true,
        },
        {
            name: 'Phuc',
            email: 'Phuc@example.com',
            password: bcrypt.hashSync('1234', 8),
            sex: 'male',
            avatar: '/images/avatar.jpg',
            phone:'0376347223',
            isAdmin: false,
            isWebmaster: false,
        },
    ],
    products: [
        {
            name: 'Áo Thun Paul Polo Mint',
            category: 'Áo Thun',
            image: '/images/paulpolomint.jpg',
            price: 500000,
            countInStock: 20,
            brand: 'Lider',
            description: 'Áo polo cổ ve lật, tay ngắn bo viền bằng vải gân dệt cùng màu. Cài khuy ẩn phía trước. Túi vuông trước ngực với hình thêu ở tay áo.Thiết kế thuộc BST Candybar Spring 2021',
            isSale: true,
            saleOff: 10,
        },
        {
            name: 'Áo Thun Knit Tanktop White',
            category: 'Áo Thun',
            image: '/images/knittanktopwhite.jpg',
            price: 300000,
            countInStock: 25,
            brand: 'Lider',
            description: 'Chất liệu: Cotton thun dệt.Áo ba lỗ cổ tim, phom gilet rộng. Áo màu trắng kem.Áo có thiết kế unisex. Áo có bo thun 2cm ở cổ và nách.Thiết kế thuộc New Arrival 5/2021.',
        },
        {
            name: 'Áo Thun Basic Tanktop White',
            category: 'Áo Thun',
            image: '/images/basictanktopwhite.jpg',
            price: 250000,
            countInStock: 20,
            brand: 'Lider',
            description: 'Chất liệu: Cotton thun. Áo ba lỗ phom rộng, cổ áo sâu, khoét nách rộng. Áo có túi nhỏ ngực trái, may bọc viền ở cổ. Thiết kế thuộc dòng sản phẩm classic của LIDER.',
        },
        {
            name: 'Áo Thun Basic Tanktop Black',
            category: 'Áo Thun',
            image: '/images/basictanktopblack.jpg',
            price: 250000,
            countInStock: 19,
            brand: 'Lider',
            description: 'Chất liệu: Cotton thun. Áo ba lỗ phom rộng, cổ áo sâu, khoét nách rộng. Áo có túi nhỏ ngực trái, may bọc viền ở cổ. Thiết kế thuộc dòng sản phẩm classic của LIDER.',
        },
        {
            name: 'Áo Sơ Mi Oversize Trắng',
            category: 'Áo Sơ Mi',
            image: '/images/somitrangowst.jpg',
            price: 450000,
            countInStock: 10,
            brand: 'OWST',
            description: 'Áo sơ mi dáng rộng, cổ ve lật, thiết kế unisex. Áo có túi trước ngực trái. Chi tiết hình in cao su nổi phía sau, áo cài khuy trước, vạt áo bầu, nẹp cổ tay.',
            isSale: true,
            saleOff: 20,
        },
        {
            name: 'Áo Sơ Mi Trắng Lider 2021',
            category: 'Áo Sơ Mi',
            image: '/images/somitranglider.jpg',
            price: 500000,
            countInStock: 15,
            brand: 'Lider',
            description: 'Áo sơ mi dáng rộng, cổ ve lật, thiết kế unisex. Áo có túi trước ngực trái. Chi tiết hình in cao su nổi phía sau, áo cài khuy trước, vạt áo bầu, nẹp cổ tay.',
            isSale: true,
            saleOff: 10,
        },
        {
            name: 'Áo Thun Polo Multicolor',
            category: 'Áo Thun',
            image: '/images/aopoloowst.jpg',
            price: 400000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: Cotton 2 chiều, dày dặn và đứng phom. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn.',
            isSale: true,
            saleOff: 30,
        },
        {
            name: 'Áo Sơ Mi Ngắn Tay O Logo',
            category: 'Áo Sơ Mi',
            image: '/images/aosomingantaylogoowst.jpg',
            price: 450000,
            countInStock: 10,
            brand: 'OWST',
            description: 'Chất liệu: 80% Cotton, 20% PolyesterÁo sơ mi phom suông rộng, hình in chuyển nhiệt không phai, không dính. Thiết kế thuộc BST Palmand FW2020.',
            isSale: true,
            saleOff: 20,
        },
        {
            name: 'Áo Sơ Mi Oversize Ngắn Tay',
            category: 'Áo Sơ Mi',
            image: '/images/aosomingantayowst.jpg',
            price: 450000,
            countInStock: 30,
            brand: 'OWST',
            description: 'Chất liệu: Cotton Viscose. Áo sơ mi phom suông rộng. Thiết kế thuộc BST Candybar Spring 2021.',
            isSale: true,
            saleOff: 30,
        },
        {
            name: 'Áo Thun Astmmetrical',
            category: 'Áo Thun',
            image: '/images/aothunasmmetricalowst.jpg',
            price: 320000,
            countInStock: 16,
            brand: 'OWST',
            description: 'Chất liệu: Cotton 2 chiều, định lượng 250gsm dày dặn. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn. Thiết kế thuộc New Arrivals 03/2021.',
        },
        {
            name: 'Áo Thun Basic Premium Black',
            category: 'Áo Thun',
            image: '/images/aothunbasicowstblack.jpg',
            price: 280000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: Cotton 2 chiều, dày dặn. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn.',
            isSale: true,
            saleOff: 40,
        },
        {
            name: 'Áo Thun Basic Premium Gray',
            category: 'Áo Thun',
            image: '/images/aothunbasicowstgray.jpg',
            price: 280000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: Cotton 2 chiều, dày dặn. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn.',
            isSale: true,
            saleOff: 40,
        },
        {
            name: 'Áo Thun Basic Premium Dark Green',
            category: 'Áo Thun',
            image: '/images/aothunbasicowstgreen.jpg',
            price: 280000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: Cotton 2 chiều, dày dặn. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn.',
            isSale: true,
            saleOff: 40,
        },
        {
            name: 'Áo Thun Basic Premium White',
            category: 'Áo Thun',
            image: '/images/aothunbasicowstwhite.jpg',
            price: 280000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: Cotton 2 chiều, dày dặn. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn.',
            isSale: true,
            saleOff: 40,
        },
        {
            name: 'Áo Thun Raw-Cut Oversize',
            category: 'Áo Thun',
            image: '/images/aothunrawcutowst.jpg',
            price: 330000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Chất liệu: Cotton, Color: Cream. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn. Thiết kế thuộc New Arrivals 03/2021.',
        },
        {
            name: 'Áo Thun Striped Logo',
            category: 'Áo Thun',
            image: '/images/aothunstripedowst.jpg',
            price: 350000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: 100% Cotton. Phom áo rộng, vai áo trễ. Bo áo dệt dày dặn không giãn. Thiết kế thuộc BST Candybar Spring 2021',
        },
        {
            name: 'Áo Thun Waffle Oversize',
            category: 'Áo Thun',
            image: '/images/aothunwaffleowst.jpg',
            price: 320000,
            countInStock: 10,
            brand: 'OWST',
            description: 'Chất liệu: Cotton, Color: Gray. Đứng form và dễ dàng phối đồ, đây chắc chắn là chiếc T-Shirt bạn không thể nào bỏ qua ',
            isSale: true,
            saleOff: 10,
        },
        {
            name: 'Áo Thun University Black',
            category: 'Áo Thun',
            image: '/images/aouniversityblack.jpg',
            price: 350000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Với hình ảnh graphic bắt mắt được in công nghệ mới lên chất vải cotton 100% 2 chiều, đứng form và dễ dàng phối đồ, áo University chắc chắn sẽ là điểm sáng cho mọi outfit của bạn ',
        },
        {
            name: 'Áo Thun University Pink',
            category: 'Áo Thun',
            image: '/images/aouniversitypink.jpg',
            price: 350000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Với hình ảnh graphic bắt mắt được in công nghệ mới lên chất vải cotton 100% 2 chiều, đứng form và dễ dàng phối đồ, áo University chắc chắn sẽ là điểm sáng cho mọi outfit của bạn ',
        },
        {
            name: 'Áo Thun University Turquoise',
            category: 'Áo Thun',
            image: '/images/aouniversityturquoise.jpg',
            price: 350000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Với hình ảnh graphic bắt mắt được in công nghệ mới lên chất vải cotton 100% 2 chiều, đứng form và dễ dàng phối đồ, áo University chắc chắn sẽ là điểm sáng cho mọi outfit của bạn ',
        },
        {
            name: 'Áo Thun University White',
            category: 'Áo Thun',
            image: '/images/aouniversitywhite.jpg',
            price: 350000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Với hình ảnh graphic bắt mắt được in công nghệ mới lên chất vải cotton 100% 2 chiều, đứng form và dễ dàng phối đồ, áo University chắc chắn sẽ là điểm sáng cho mọi outfit của bạn ',
        },
        {
            name: 'Pelican Hoodie',
            category: 'Hoodie',
            image: '/images/pelicanhoodie.jpg',
            price: 550000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: 100% Cotton. Nếu bạn cần tìm một chiếc hoodie đơn giản, oversized và đứng form thì Pelican Hoodie chắc chắn là sản phẩm bạn không thể bỏ qua ',
        },
        {
            name: 'Rainbow Logo Hoodie',
            category: 'Hoodie',
            image: '/images/rainbowhoodie.jpg',
            price: 550000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: 100% Cotton. Nếu bạn cần tìm một chiếc hoodie đơn giản, oversized và đứng form thì Rainbow Hoodie chắc chắn là sản phẩm bạn không thể bỏ qua ',
        },
        {
            name: 'Áo Thun Alone Ted',
            category: 'Áo Thun',
            image: '/images/aothunalonegamble.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Họa tiết chú gấu zombie vừa đáng yêu vừa cá tính được in sắc nét lên vải cotton 100% 2 chiều, mực in chìm vào từng thớ vải. Áo đứng form, đường may chắc chắn, tỉ mỉ, không gây nóng hay khó chịu khi mặc.',
        },
        {
            name: 'Quần Burning G White',
            category: 'Quần',
            image: '/images/burninggpants.jpg',
            price: 500000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Một chiếc quần cực kì phù hợp để diện hàng ngày, với form BOOTCUT thoải mái và tôn chiều cao, mặt sau kết hợp giữa 2 công nghệ thêu đan xen nhau, tạo nên một logo GAMBLE ấn tượng nhưng lại mềm mại, dễ chịu khi mặc. Sản phẩm đã có mặt tại store, khuyến khích các bạn đến tận nơi để trải nghiệm chất lượng sản phẩm ',
        },
        {
            name: 'Quần Half Tie-Dye Blue',
            category: 'Quần',
            image: '/images/halftiedyepants.jpg',
            price: 500000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Một chiếc quần cực kì tiện lợi, với form BOOTCUT thoải mái và tôn chiều cao, được cách điệu bằng đường phối lạ mắt, cùng công nghệ Tie-Dye đầy phóng khoáng giúp thu hút mọi ánh nhìn. Tất cả sản phẩm đều được sử dụng công nghệ 𝘛𝘐𝘌-𝘋𝘠𝘌 thủ công, do đó mỗi sản phẩm đều sẽ là một bản thể riêng và không trùng lặp! Hãy nhanh tay sở hữu ngay sản phẩm có thể nói là "Limited" này nhé ',
        },
        {
            name: 'Quần Chessy Black',
            category: 'Quần',
            image: '/images/chessypantsblack.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Một chiếc quần Khaki được phát triển trên form Bootcut. Chi tiết vải trắng và đen đan xen nhau ở gối được lấy ý tưởng từ bàn cờ vua, đây là một chi tiết mà Gamble rất tâm đắc. Khi mua sản phẩm bạn sẽ được tặng kèm Belt dành riêng cho quần Chessy',
            isSale: true,
            saleOff:20,
        },
        {
            name: 'Quần Chessy White',
            category: 'Quần',
            image: '/images/chessypantswhite.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Một chiếc quần Khaki được phát triển trên form Bootcut. Chi tiết vải trắng và đen đan xen nhau ở gối được lấy ý tưởng từ bàn cờ vua, đây là một chi tiết mà Gamble rất tâm đắc. Khi mua sản phẩm bạn sẽ được tặng kèm Belt dành riêng cho quần Chessy',
            isSale: true,
            saleOff:20,
        },
        {
            name: 'Quần Sweatpants Gamble Black',
            category: 'Quần',
            image: '/images/gwsweatpantsblack.jpg',
            price: 450000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Quần có 2 túi xẻ sâu phía trước, túi vuông phía sau. Lưng thun co giãn (+10cm), điều chỉnh bằng dây rút. Đáy quần trễ, gấu quần với đường may sống',
        },
        {
            name: 'Quần Sweatpants Gamble Maya',
            category: 'Quần',
            image: '/images/gwsweatpantsmaya.jpg',
            price: 450000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Quần có 2 túi xẻ sâu phía trước, túi vuông phía sau. Lưng thun co giãn (+10cm), điều chỉnh bằng dây rút. Đáy quần trễ, gấu quần với đường may sống',
        },
        {
            name: 'Quần Sweatpants Gamble Sahara',
            category: 'Quần',
            image: '/images/gwsweatpantssahara.jpg',
            price: 450000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Quần có 2 túi xẻ sâu phía trước, túi vuông phía sau. Lưng thun co giãn (+10cm), điều chỉnh bằng dây rút. Đáy quần trễ, gấu quần với đường may sống',
        },
        {
            name: 'Quần Track Pants Blue',
            category: 'Quần',
            image: '/images/gwtrackpantsblue.jpg',
            price: 450000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Một chiếc quần cực kì tiện lợi, thoải mái, được cách điệu bằng đường phối lạ mắt, đầy phóng khoáng giúp thu hút mọi ánh nhìn. Hãy nhanh tay sở hữu ngay sản phẩm có thể nói là "Limited" này nhé ',
        },
        {
            name: 'Quần Track Pants Orange',
            category: 'Quần',
            image: '/images/gwtrackpantsorange.jpg',
            price: 450000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Một chiếc quần cực kì tiện lợi, thoải mái, được cách điệu bằng đường phối lạ mắt, đầy phóng khoáng giúp thu hút mọi ánh nhìn. Hãy nhanh tay sở hữu ngay sản phẩm có thể nói là "Limited" này nhé ',
        },
        {
            name: 'Quần Track Pants Red',
            category: 'Quần',
            image: '/images/gwtrackpantsred.jpg',
            price: 450000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Một chiếc quần cực kì tiện lợi, thoải mái, được cách điệu bằng đường phối lạ mắt, đầy phóng khoáng giúp thu hút mọi ánh nhìn. Hãy nhanh tay sở hữu ngay sản phẩm có thể nói là "Limited" này nhé ',
        },
        {
            name: 'GRADATION JEANS',
            category: 'Quần',
            image: '/images/gradationjeanowst.jpg',
            price: 749000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: JEANS, Color: BLUE',
        },
        {
            name: 'CURVE JEANS BLACK',
            category: 'Quần',
            image: '/images/curvejeanblackowst.jpg',
            price: 749000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: JEANS, Color: BLACK',
        },
        {
            name: 'Quần JOGGER BLACK',
            category:'Quần',
            image: '/images/quanjoggerowstblack.jpg',
            price: 390000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Chất liệu: 100% COTTON, Color: BLACK',
        },
        {
            name: 'Quần JOGGER LIGHT GRAY',
            category: 'Quần',
            image: '/images/quanjoggerowstlightgray.jpg',
            price: 390000,
            countInStock: 18,
            brand: 'OWST',
            description: 'Chất liệu: 100% COTTON, Color: LIGHT GRAY',
        },
        {
            name: 'Quần JOGGER DARK GRAY',
            category: 'Quần',
            image: '/images/quanjoggerowstdarkgray.jpg',
            price: 390000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: 100% COTTON, Color: DARK GRAY',
        },
        {
            name: 'Quần SWEATSHORT BLACK',
            category: 'Quần',
            image: '/images/shortowstblack.jpg',
            price: 350000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Chất liệu: 100% COTTON, Color: BLACK',
        },
        {
            name: 'Quần SWEATSHORT NAVY',
            category: 'Quần',
            image: '/images/shortowstnavy.jpg',
            price: 350000,
            countInStock: 18,
            brand: 'OWST',
            description: 'Chất liệu: 100% COTTON, Color: NAVY',
        },
        {
            name: 'Quần BASIC SWEATSHORT GRAY',
            category: 'Quần',
            image: '/images/shortowstgray.jpg',
            price: 350000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Chất liệu: 100% COTTON, Color: GRAY',
        },
        {
            name: 'Quần PATTERN LACVIET',
            category: 'Quần',
            image: '/images/quanlacvietowst.jpg',
            price: 590000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: KAKI. Thiết kế thuộc BST LACVIET Summer 2021.',
        },
        {
            name: 'Quần TAPO Shorts BLACK',
            category: 'Quần',
            image: '/images/quanshortliderden.jpg',
            price: 620000,
            countInStock: 20,
            brand: 'LIDER',
            description: 'Quần lửng bermuda ống suông thẳng, đường may cạnh sườn có chi tiết may ngược trang trí.',
        },
        {
            name: 'Quần TAPO Shorts WHITE',
            category: 'Quần',
            image: '/images/quanshortlidertrang.jpg',
            price: 620000,
            countInStock: 15,
            brand: 'LIDER',
            description: 'Quần lửng bermuda ống suông thẳng, đường may cạnh sườn có chi tiết may ngược trang trí.',
        },
        {
            name: 'UNCLE Jeans',
            category: 'Quần',
            image: '/images/unclejeanlider.jpg',
            price: 790000,
            countInStock: 20,
            brand: 'LIDER',
            description: 'Thiết kế thuộc dòng sản phẩm classic của LIDER',
        },
        {
            name: 'TOM Jeans',
            category: 'Quần',
            image: '/images/tomjeanlider.jpg',
            price: 820000,
            countInStock: 25,
            brand: 'LIDER',
            description: 'Thiết kế thuộc dòng sản phẩm classic của LIDER',
        },
        {
            name: 'Quần ORI Black',
            category: 'Quần',
            image: '/images/quanoridenlider.jpg',
            price: 720000,
            countInStock: 16,
            brand: 'LIDER',
            description: 'Thiết kế thuộc dòng sản phẩm classic của LIDER',
        },
        {
            name: 'Quần ORI White',
            category: 'Quần',
            image: '/images/quanoritranglider.jpg',
            price: 720000,
            countInStock: 20,
            brand: 'LIDER',
            description: 'Thiết kế thuộc dòng sản phẩm classic của LIDER',
        },
        {
            name: 'Quần CARGO CEMENT',
            category: 'Quần',
            image: '/images/quancargolider.jpg',
            price: 580000,
            countInStock: 25,
            brand: 'LIDER',
            description: 'Quần ống suông rộng phom unisex với độ dài phủ gót. Quần có 2 túi hộp có nắp.',
        },
        {
            name: 'Quần DEEP SEA',
            category: 'Quần',
            image: '/images/quandeepsealider.jpg',
            price: 750000,
            countInStock: 20,
            brand: 'LIDER',
            description: 'Quần ống rộng xếp li giữa với túi hai bên, lưng thun co giãn (+10cm) phía sau.',
        },
        {
            name: 'Áo Khoác SIVINA Black',
            category: 'Áo Khoác',
            image: '/images/aokhoacsivinablack.jpg',
            price: 850000,
            countInStock: 20,
            brand: 'LIDER',
            description: 'Áo khoác phom rộng có nón, tay áo bo chun. Thiết kế unisex.',
            isSale: true,
            saleOff:20,
        },
        {
            name: 'Áo Khoác SIVINA Pink',
            category:'Áo Khoác',
            image: '/images/aokhoacsivinapink.jpg',
            price: 850000,
            countInStock: 25,
            brand: 'LIDER',
            description: 'Áo khoác phom rộng có nón, tay áo bo chun. Thiết kế unisex.',
            isSale: true,
            saleOff:20,
        },
        {
            name: 'Áo Khoác SUNSET',
            category: 'Áo Khoác',
            image: '/images/aokhoacsunset.jpg',
            price: 700000,
            countInStock: 25,
            brand: 'LIDER',
            description: 'Áo khoác cổ cao có mũ trùm đầu kèm dây rút, có túi đắp phía trước.',
            isSale: true,
            saleOff:10,
        },
        {
            name: 'Áo Blazer COMTE',
            category: 'Blazer',
            image: '/images/aocometblazer.jpg',
            price: 850000,
            countInStock: 30,
            brand: 'LIDER',
            description: 'Áo khoác blazer phom rộng lửng, ve áo lật.',
        },
        {
            name: 'Áo Blazer GREYLINE',
            category: 'Blazer',
            image: '/images/aogreylineblazer.jpg',
            price: 990000,
            countInStock: 30,
            brand: 'LIDER',
            description: 'Áo khoác blazer phom rộng lửng, ve áo lật.',
        },
        {
            name: 'Áo Khoác BLUEBERRY',
            category: 'Áo Khoác',
            image: '/images/aokhoacblueberry.jpg',
            price: 820000,
            countInStock: 25,
            brand: 'LIDER',
            description: 'Áo khoác phom ngắn, ve áo lật, nút gài giữa áo.',
        },
        {
            name: 'Áo Khoác COOKIE',
            category: 'Áo Khoác',
            image: '/images/aocookiecoat.jpg',
            price: 999000,
            countInStock: 25,
            brand: 'LIDER',
            description: 'Áo khoác dáng trench coat kèm dây thắt rời, cổ áo đôi.',
        },
        {
            name: 'Áo Khoác GINGHAM',
            category: 'Áo Khoác',
            image: '/images/aokhoacgingham.jpg',
            price: 590000,
            countInStock: 20,
            brand: 'OWST',
            description: 'Chất liệu: COTTON. Có túi hộp phía trước, khuy cài trước',
        },
        {
            name: 'Áo Khoác LOGO Gray',
            category: 'Áo Khoác',
            image: '/images/aokhoaclogoowstgray.jpg',
            price: 599000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Chất liệu: COTTON, Color: GRAY',
        },
        {
            name: 'Áo Khoác LOGO Black',
            category: 'Áo Khoác',
            image: '/images/aokhoaclogoowstden.jpg',
            price: 599000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Chất liệu: COTTON, Color: BLACK',
        },
        {
            name: 'Áo Khoác LACVIET',
            category: 'Áo Khoác',
            image: '/images/aokhoaclacviet.jpg',
            price: 650000,
            countInStock: 25,
            brand: 'OWST',
            description: 'Chất liệu: COTTON, Color: BLACK. Thiết kế thuộc BST LACVIET Summer 2021.',
        },
        {
            name: 'Áo Khoác GARNITURE',
            category: 'Áo Khoác',
            image: '/images/aokhoacgarnitureblack.jpg',
            price: 750000,
            countInStock: 30,
            brand: 'OWST',
            description: 'Áo khoác da dáng bomber, cổ ve lật, lai áo bo chun.',
        },
        {
            name: 'Áo Khoác Gamble Varsity/Blood',
            category: 'Áo Khoác',
            image: '/images/gwvarsityjacketblood.jpg',
            price: 990000,
            countInStock: 0,
            brand: 'Gamble',
            description: 'Là môt item quen thuộc trên các sân thể thao trường học, nhưng khi đến Gamble, chiếc áo Varsity Jacket đã được nâng tầm và cách điệu phù hợp với mọi sự kiện, hoạt động và thời điểm. Gamble Varsity Jacket chắc chắn sẽ đồng hành trên chặng đường dài cùng bạn.',
        },
        {
            name: 'Áo Khoác Gamble Varsity/Hunter',
            category: 'Áo Khoác',
            image: '/images/gwvarsityjackethunter.jpg',
            price: 990000,
            countInStock: 5,
            brand: 'Gamble',
            description: 'Là môt item quen thuộc trên các sân thể thao trường học, nhưng khi đến Gamble, chiếc áo Varsity Jacket đã được nâng tầm và cách điệu phù hợp với mọi sự kiện, hoạt động và thời điểm. Gamble Varsity Jacket chắc chắn sẽ đồng hành trên chặng đường dài cùng bạn.',
        },
        {
            name: 'Áo Khoác Gamble Varsity/Nightmare',
            category: 'Áo Khoác',
            image: '/images/gwvarsityjacketnightmare.jpg',
            price: 990000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Là môt item quen thuộc trên các sân thể thao trường học, nhưng khi đến Gamble, chiếc áo Varsity Jacket đã được nâng tầm và cách điệu phù hợp với mọi sự kiện, hoạt động và thời điểm. Gamble Varsity Jacket chắc chắn sẽ đồng hành trên chặng đường dài cùng bạn.',
        },
        {
            name: 'Gamble Track Jacket/Baby Blue',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketbabyblue.jpg',
            price: 650000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Gamble Track Jacket/Black',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketblack.jpg',
            price: 650000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Gamble Track Jacket/Dark Grey',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketdarkgrey.jpg',
            price: 650000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Gamble Track Jacket/Grey',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketdarkgrey.jpg',
            price: 650000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Gamble Track Jacket/Lavender',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketlavender.jpg',
            price: 650000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Gamble Track Jacket/Red',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketred.jpg',
            price: 650000,
            countInStock: 15,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Gamble Track Jacket/White',
            category: 'Áo Khoác',
            image: '/images/gwtrackjacketwhite.jpg',
            price: 650000,
            countInStock: 15,
            brand: 'Gamble',
            description: 'Gamble Track Jacket. Là chiếc Track Jacket đầu tiên được GAMBLE ra mắt, Gamble Track Jacket cũng không thể thiếu chi tiết đặc trưng được ưa chuộng của dòng áo khoác GAMBLE:  2-Way Zipper - Khóa kéo 2 đầu thời trang  Inside Pocket - Thiết kế túi trong tiện dụng. Dòng chữ GAMBLE và logo ở 2 cánh tay được thêu chất lượng cao Đặc biệt, với form dáng Oversize và chất vải thể thao Tricot vừa bền chắc, vừa thoáng mát, Gamble Track Jacket chắc hẳn là item mà bạn có thể diện ở trong bất kì thời tiết cũng như hoạt động nào.',
            isSale: true,
            saleOff:30,
        },
        {
            name: 'Áo Hoodie Washed Cream',
            category: 'Hoodie',
            image: '/images/0912hoodiewashedbe.jpg',
            price: 629000,
            countInStock: 30,
            brand: '0912',
            description: 'Vintage Washed, Chất liệu: 100% French Terry Cotton',
        },
        {
            name: 'Áo Hoodie Washed Black',
            category: 'Hoodie',
            image: '/images/0912hoodiewashedblack.jpg',
            price: 629000,
            countInStock: 0,
            brand: '0912',
            description: 'Vintage Washed, Chất liệu: 100% French Terry Cotton',
        },
        {
            name: 'Áo Hoodie Washed Logo',
            category: 'Hoodie',
            image: '/images/0912logohoodiewashed.jpg',
            price: 629000,
            countInStock: 0,
            brand: '0912',
            description: 'Vintage Washed, Chất liệu: 100% French Terry Cotton',
        },
        {
            name: 'Nón T-Logo Blue',
            category: 'Phụ Kiện',
            image: '/images/nonowstblue.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Blue/Grey ',
            category: 'Phụ Kiện',
            image: '/images/nonowstbluegrey.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Maroon ',
            category: 'Phụ Kiện',
            image: '/images/nonowstmaroon.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Red/Black ',
            category: 'Phụ Kiện',
            image: '/images/nonowstredblack.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Black ',
            category: 'Phụ Kiện',
            image: '/images/nonowstblack.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Gray/Black ',
            category: 'Phụ Kiện',
            image: '/images/nonowstblackgray.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Black/Grey ',
            category: 'Phụ Kiện',
            image: '/images/nonowstblackgrey.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Nón T-Logo Gray ',
            category: 'Phụ Kiện',
            image: '/images/nonowstgrey.jpg',
            price: 230000,
            countInStock: 15,
            brand: 'OWST',
            description: 'Nón T-Logo là một item đơn giản, mang họa tiết logo OWST cùng với chất liệu được nâng cấp sao cho thoải mái. Đây chắc chắn sẽ là phụ kiện vừa tiện ích, vừa đậm cá tính cho những bạn năng động.',
        },
        {
            name: 'Áo Khoác Denim DNA',
            category: 'Áo Khoác',
            image: '/images/aokhoacdnadenim.jpg',
            price: 900000,
            countInStock: 0,
            brand: 'Louis Vuitton',
            description: 'Chiếc áo khoác DNA Denim này mang đến sự biến tấu của Virgil Abloh cho một hình bóng cổ điển.',
        },
        {
            name: 'Áo Khoác Monogram Bomber',
            category: 'Áo Khoác',
            image: '/images/aokhoacmonogramlv.jpg',
            price: 900000,
            countInStock: 0,
            brand: 'Sain Laurent',
            description: 'Các chi tiết bao gồm chữ ký LV màu nước trên tay áo và các đường gân dệt kim.',
        },
        {
            name: 'AOS Hoodie Black',
            category: 'Hoodie',
            image: '/images/aoshoodieblack.jpg',
            price: 750000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'Nếu bạn cần tìm một chiếc hoodie nổi bật, oversized và đứng form thì AOS Hoodie chắc chắn là sản phẩm bạn không thể bỏ qua. Từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.',
        },
        {
            name: 'Big Logo Full Zip Hoodie/Eastern',
            category: 'Hoodie',
            image: '/images/gwbiglogohoodie.jpg',
            price: 700000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'Nếu bạn cần tìm một chiếc hoodie nổi bật, oversized và đứng form thì Big Logo Hoodie chắc chắn là sản phẩm bạn không thể bỏ qua. Từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.',
        },   
        {
            name: 'GW Full Zip Hoodie/Blood',
            category: 'Hoodie',
            image: '/images/gwfullziphoodieblood.jpg',
            price: 500000,
            countInStock: 0,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        },   
        {
            name: 'GW Full Zip Hoodie/Capuchino',
            category: 'Hoodie',
            image: '/images/gwfullziphoodiecapuchino.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        }, 
        {
            name: 'GW Full Zip Hoodie/Cookie',
            category: 'Hoodie',
            image: '/images/gwfullziphoodiecookie.jpg',
            price: 500000,
            countInStock: 0,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        },  
        {
            name: 'GW Full Zip Hoodie/Grey',
            category: 'Hoodie',
            image: '/images/gwfullziphoodiegrey.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        },  
        {
            name: 'GW Full Zip Hoodie/Maroon',
            category: 'Hoodie',
            image: '/images/gwfullziphoodiemaroon.jpg',
            price: 500000,
            countInStock: 20,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        }, 
        {
            name: 'GW Full Zip Hoodie/Mint',
            category: 'Hoodie',
            image: '/images/gwfullziphoodiemint.jpg',
            price: 500000,
            countInStock: 0,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        },
        {
            name: 'GW Full Zip Hoodie/Rosie',
            category: 'Hoodie',
            image: '/images/gwfullziphoodierosie.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        },
        {
            name: 'GW Full Zip Hoodie/White',
            category: 'Hoodie',
            image: '/images/gwfullziphoodiewhite.jpg',
            price: 500000,
            countInStock: 10,
            brand: 'Gamble',
            description: 'GW FULLZIP HOODIE là dòng sản phẩm đặc trưng của Gamble Worldwide. Là Local Brand đầu tiên khởi xướng và phát triển dòng sản phẩm FULLZIP HOODIE với form dáng OVERSIZED thoải mái, không kén dáng người mặc. Với những chi tiết được đầu tư tỉ mỉ như 2-WAY ZIPPER - Khóa kéo 2 đầu tiện lợi và INSIDE POCKET - Thiết kế túi trong do chính Gamble sáng tạo. GW FULLZIP HOODIE đã được release hơn 50 phiên bản màu khác nhau, từng phiên bản là từng chất liệu vải được Gamble dày công chọn lựa, với mong muốn đem đến một trải nghiệm tốt nhất cho khách hàng.Đây chắc chắn là chiếc FULLZIP HOODIE mà bạn đang tìm kiếm!',
        },
    ],

};
export default data;